all:
  children:
    cisco:
      hosts:
        R1:
          ansible_host: 192.168.11.120
        R2:
          ansible_host: 192.168.11.121
        IOU_R:
          ansible_host: 192.168.11.123
    
    cisco_sw:
      hosts:
        IOU_SW:
          ansible_host: 192.168.11.124
