all:
  children:
    cisco:
      hosts:
        R1:
          ansible_host: 192.168.11.120
        R2:
          ansible_host: 192.168.11.121
        IOU_R:
          ansible_host: 192.168.11.123
    
    cisco_sw:
      hosts:
        IOU_SW:
          ansible_host: 192.168.11.124

# --- ADD THIS SECTION ---
    fortinet:
      hosts:
        FW01:
          ansible_host: 192.168.11.150 # Replace with your FW IP
      vars:
        ansible_connection: httpapi
        ansible_network_os: fortinet.fortios.fortios
        ansible_httpapi_use_ssl: yes
        ansible_httpapi_validate_certs: no
        ansible_httpapi_port: 443
        ansible_httpapi_session_key: '{"access_token":"Nnmsbrwykx8gpwwk0Hs1km95ttG7Q4"}'

    cisco_asa:
      hosts:
        lab_asa:
          ansible_host: 192.168.11.163
      vars:
        ansible_user: ansible_asa
        ansible_password: "{{ vault_asa_password }}"
        ansible_network_os: cisco.asa.asa
        ansible_connection: ansible.netcommon.network_cli

        # --- ADD THESE FOR PRIVILEGE ELEVATION ---
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: "{{ vault_asa_password }}" # Uses your vault password for enable mode
        
        # --- BUMP TIMEOUTS ---
        ansible_netcommon_timeout: 60
        ansible_netcommon_connect_timeout: 60

