---
- name: FortiGate Automation and Backup
  hosts: fortigates
  gather_facts: true
  collections:
    - fortinet.fortios

  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ ansible_env.HOME }}/ansible_cisco_lab/backups"
        state: directory
      delegate_to: localhost
      tags: [always] # Always runs Must

    - name: Backup FortiGate Config
      fortios_monitor_fact:
        access_token: "{{ vault_forti_token }}"
        vdom: "root"
        selector: "system_config_backup"
        params:
          scope: "global"
      register: backup_data
      tags: [backup]

    - name: Save Backup to File
      copy:
        content: "{{ backup_data.meta.raw }}"
        dest: "{{ workspace_backup_path | default(ansible_env.HOME + '/ansible_cisco_lab/backups') }}/{{ custom_backup_filename | default(inventory_hostname + '_' + ansible_date_time.date + '.conf') }}"
      delegate_to: localhost
      tags: [backup]

    - name: Create Address Objects
      fortios_firewall_address:
        access_token: "{{ vault_forti_token }}"
        vdom: "root"
        state: "present"
        firewall_address:
          name: "{{ item.name }}"
          subnet: "{{ item.ip }} {{ item.mask }}"
      loop:
        - { name: "Server_Farm", ip: "10.10.10.0", mask: "255.255.255.0" }
      tags: [config]

    - name: Create LAN to WAN Policy
      fortios_firewall_policy:
        access_token: "{{ vault_forti_token }}"
        vdom: "root"
        state: "present"
        firewall_policy:
          policyid: 1
          name: "Allow_Internet"
          srcintf: [{ "name": "port2" }]
          dstintf: [{ "name": "port1" }]
          srcaddr: [{ "name": "Server_Farm" }]
          dstaddr: [{ "name": "all" }]
          action: "accept"
          service: [{ "name": "ALL" }]
          nat: "enable"
      tags: [config]
