---
- name: Configure Cisco Routers
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure MOTD Banner
      cisco.ios.ios_banner:
        banner: motd
        text: |
          ---------------------------------------
          WARNING: Authorized Access Only
          Managed by Ansible & Jenkins with GitHub
          Automation with Webhook + ngrock , GNS3
          ---------------------------------------
        state: present

    - name: Configure Loopback 100 (The Universal Way)
      cisco.ios.ios_config:
        lines:
          - description Configured by Ansible
          - ip address 192.168.100.1 255.255.255.255
          - no shutdown
        parents: interface Loopback100
        
    - name: Configure Loopback 200 (The Universal Way)
      cisco.ios.ios_config:
        lines:
          - description Configured by Ansible + gitpull
          - ip address 192.168.200.1 255.255.255.255
          - no shutdown
        parents: interface Loopback200
      # 'parents' enters the interface mode
      # 'lines' executes the commands inside that mode

    - name: Save Configuration
      cisco.ios.ios_config:
        save_when: modified

