---
- name: Backup Cisco Router Config
  hosts: cisco
  connection: network_cli
  gather_facts: no

  vars:
    current_date: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

  tasks:
    - name: Create backup directory
      file:
        path: "{{ playbook_dir }}/../backups"
        state: directory
        mode: '0755'

    - name: Backup running config
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: "{{ playbook_dir }}/../backups"
          filename: "backup_{{ inventory_hostname }}_{{ current_date }}.cfg"
      register: backup_output

    - name: Display backup location
      debug:
        msg: "Backup Saved to {{ backup_output.backup_path }}"
